### ISSUE TITLE
How to generate android project on Windows without using Tegra?

### ISSUE THREAD

**Issue by kepkin** [taka-no-me/android-cmake#39]
Hi, I want to use only android ndk & sdk for build, but don't want to install Tegra Studio. I'll just not be able to install it on CI server. Is it possible?

I tried to comment ```CMAKE_SYSTEM_NAME Android``` and was able to generate Visual Studio project, but it fails to build. For some reason it still uses VS's linker instead of linker from NDK. I've check CMakeCache.txt and it points to NDK linker:
```
CMAKE_LINKER:PATH=C:/Users/aln/android-ndk-r10d/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ld.exe
```

Could you please suggest anything?

**Comment by taka-no-me** [comment]
I would say that this project do not support using Visual Studio for Android build at all. I suggest you to try another CMake generators.
