### ISSUE TITLE
How to use android_native_app_glue?

### ISSUE THREAD

**Issue by archSeer** [taka-no-me/android-cmake#4]
My code requires the use of `android_native_app_glue` wrapper, found in `ANDROID_NDK/sources/android`. The way it was previously included in Android.mk was by using 

    LOCAL_STATIC_LIBRARIES := android_native_app_glue

How can I use this in cmake?

**Comment by taka-no-me** [comment]
You can use `android_ndk_import_module_native_app_glue()` from `AndroidNdkModules.cmake` to import it
