### ISSUE TITLE
Integrate this in the official Cmake distribution

### ISSUE THREAD

**Issue by bhack** [taka-no-me/android-cmake#64]
@steveire @bradking It would be great if Cmake could officially integrate android support with this.

**Comment by bradking** [comment]
This would be best discussed on the CMake [developer mailing list](http://www.cmake.org/mailman/listinfo/cmake-developers) for a broader audience.  You could raise this topic over there.

**Comment by bhack** [comment]
@taka-no-me Are you interested to discuss this in the dev mailing list?
