### ISSUE TITLE
*find_path* and *find_library* doesn't seem to work 

### ISSUE THREAD

**Issue by septag** [taka-no-me/android-cmake#95]
I'm trying to use _find_path_ and _find_library_ to find headers and libraries for local files that I built for android. The path is correct but it doesn't find anything. 
Here's an example:

```
set(LIBUV_ROOT_DIR "[Path to libuv local files]")
find_path(LIBUV_INCLUDE_DIR
     NAMES uv.h
     HINTS ${LIBUV_ROOT_DIR}/include
)
```

LIBUV_INCLUDE_DIR-Not-Found

do these functions work for android-toolchain ?

**Comment by manjia** [comment]
I had the same problem and I just confirmed that adding the NO_CMAKE_FIND_ROOT_PATH flag to find_* instruction makes it work properly.

The solution was originally posted here:
https://code.google.com/p/android/issues/detail?id=214412

Someone in the same thread also proposes another workaround but I'm fine with this one so i didn't try it

**Comment by septag** [comment]
Thanks, that solved the problem

**Comment by manjia** [comment]
I cannot  believe that in 2016 we are still stuck with THIS KIND OK SHIT CODE. VERY DISAPPOINTED.

**Comment by ikcalB** [comment]
ran into the same issue/solution.

Why is this even necessary!? According to docs, cmake should continue to search in HINTS/PATHS. It does not seem to do that, without specifying `NO_CMAKE_ROOT_PATH`.
Bug?
